control_flow_indent_style = "Block"
struct_indent_style = "Block"
binop_separator = "Back"
chain_indent = "Visual"
condense_wildcard_suffixes = true
error_on_line_overflow = false
error_on_line_overflow_comments = false
brace_style = "PreferSameLine"
fn_single_line = true
where_single_line = true
force_explicit_abi = false
format_strings = true
max_width = 95
newline_style = "Unix"
ideal_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_groups = true
match_block_trailing_comma = true
where_trailing_comma = true
normalize_comments = false
struct_lit_multiline_style = "ForceMulti"
